# Generated by Django 4.2.5 on 2023-10-27 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surnameClient', models.TextField(verbose_name='Фамилия')),
                ('nameClient', models.TextField(verbose_name='Имя')),
                ('fatherNameClient', models.TextField(verbose_name='Отчество')),
            ],
            options={
                'verbose_name': 'Клиенты банка',
            },
        ),
        migrations.CreateModel(
            name='Deposites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depositeCode', models.IntegerField(verbose_name='Код вклада')),
                ('depositeName', models.CharField(choices=[('Cumulative', 'накопительный'), ('Universal', 'универсальный')], max_length=30, verbose_name='Наименование депозита')),
                ('minDepositePeriod', models.IntegerField(verbose_name='Минимальный срок вклада')),
                ('minDepositeValue', models.IntegerField(verbose_name='Минимальная сумма вклада')),
                ('currencyCode', models.CharField(choices=[('Rub', 'Рубли'), ('Us', 'Доллары'), ('Eu', 'Евро')], max_length=30, verbose_name='Код валюты')),
                ('interestRate', models.IntegerField(verbose_name='Процентная ставка, годовая')),
            ],
            options={
                'verbose_name': 'Виды вкладов',
            },
        ),
        migrations.CreateModel(
            name='DepositsRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surnameClient', models.TextField(verbose_name='Фамилия')),
                ('nameClient', models.TextField(verbose_name='Имя')),
                ('fatherNameClient', models.TextField(verbose_name='Отчество')),
                ('depositeCode', models.IntegerField(verbose_name='Код вклада')),
                ('depositeDateStart', models.DateField(verbose_name='дата открытия вклада')),
                ('depositeDateEnd', models.DateField(verbose_name='дата закрытия вклада')),
                ('depositeSum', models.IntegerField(verbose_name='сумма вкалада')),
                ('depositeStatus', models.CharField(choices=[('close', 'закрыт'), ('in progress', 'действует')], max_length=20, verbose_name='Статус вклада')),
                ('surnamePersons', models.TextField(verbose_name='Фамилия')),
                ('namePersons', models.TextField(verbose_name='Имя')),
                ('fatherNamePersons', models.TextField(verbose_name='Отчество')),
            ],
            options={
                'verbose_name': 'Регистрация вкладов',
            },
        ),
        migrations.CreateModel(
            name='ExchangeRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratesName', models.CharField(choices=[('rub', 'рубли'), ('us', 'доллары США'), ('eu', 'евро')], max_length=40, verbose_name='Наименование')),
                ('exchangeRate', models.FloatField(verbose_name='Обменный курс')),
            ],
            options={
                'verbose_name': 'Обменный курс',
            },
        ),
        migrations.CreateModel(
            name='Persons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surnamePersons', models.TextField(verbose_name='Фамилия')),
                ('namePersons', models.TextField(verbose_name='Имя')),
                ('fatherNamePersons', models.TextField(verbose_name='Отчество')),
                ('jobTitlePersons', models.TextField(verbose_name='Должности')),
                ('salaryPersons', models.IntegerField(verbose_name='Оклад')),
            ],
            options={
                'verbose_name': 'Сотрудники банка и их должности',
            },
        ),
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'заявка', 'verbose_name_plural': 'заявок'},
        ),
        migrations.AlterField(
            model_name='articles',
            name='full_text',
            field=models.TextField(verbose_name='содержание'),
        ),
    ]
