# Generated by Django 4.2.5 on 2023-11-05 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_alter_clients_options_alter_deposites_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposites',
            name='currencyCode',
            field=models.CharField(max_length=6, verbose_name='Код валюты'),
        ),
        migrations.AlterField(
            model_name='deposites',
            name='depositeName',
            field=models.CharField(max_length=10, verbose_name='Наименование депозита'),
        ),
    ]
