# Generated by Django 4.2.5 on 2023-11-22 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_alter_deposites_currencycode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposites',
            name='currencyCode',
            field=models.CharField(choices=[('Rub', 'Рубли'), ('Us', 'Доллары'), ('Eu', 'Евро')], max_length=6, verbose_name='Код валюты'),
        ),
        migrations.AlterField(
            model_name='deposites',
            name='depositeName',
            field=models.CharField(choices=[('Cumulative', 'накопительный'), ('Universal', 'универсальный')], max_length=10, verbose_name='Наименование депозита'),
        ),
    ]
